### ISSUE TITLE
Callback never returns when calling retrieve synchronously 

### ISSUE THREAD

**Issue by jjvargas** [Jearil/SimpleNoSQL#16]
I have implemented a method to retrieve results from a bucket in a Synchronous way. But the callback never returns. Any idea?

public <T> List<T> getAll(String bucket, Class<T> type) {

```
    final CountDownLatch latch = new CountDownLatch(1);
    final List<T> result = new ArrayList<T>();
    try {

        NoSQL.with(contextReference.get()).using(type).bucketId(bucket).retrieve(
                new RetrievalCallback<T>() {
                    @Override
                    public void retrievedResults(List<NoSQLEntity<T>> noSQLEntities) {
                        System.out.println("NEVER RETURNS!!!!");

                        for (int i = 0; i < noSQLEntities.size(); i++) {
                            result.add(noSQLEntities.get(i).getData());
                        }
                        latch.countDown();
                    }
                });
        latch.await();
        return result;
    } catch (Exception e) {
        return null;
    }


}
```

**Comment by eyecreate** [comment]
I've seen this happen too when trying to use Synchronous getting.
I'm pretty certain from some testing the reason why this happens is because of QueryDelivery. All callbacks that happen seem to go through this class and the class is initialized in NoSQL with Looper.getMainLooper(). This means, when either SynchronousRetrieval or manual sync code uses something like CountDownLatch, the await locks up the thread being used(which in most cases will be the main thread), which then locks up the QueryDelivery from calling any callbacks, even if they were made off main thread. The safest way to get results here is to create a HandlerThread for NoSQL/QueryDelivery. I've made a proposed change.

**Comment by Jearil** [comment]
hmm, but delivery should be possible on the main thread. You can always override QueryDelivery using NoSQL.withUsing. For simple use-cases, if people then try to populate their UI with the results of the data retrieval it will error since it won't be running on the main thread. You really should never be using a synchronous call on the main thread and blocking your UI. I think perhaps a better solution would be to check what thread the synchronous calls are coming from and if it's the UI thread, either throw an error or at least log something.

**Comment by eyecreate** [comment]
It sounds like if it's important for the current design to dispatch on the main thread, then synchronous calls will run into issues if not specifically run outside main thread. As long as some docs or error mention this issue, it would help people stumbling on this without knowing how the library internals work.

**Comment by Jearil** [comment]
Very good point. I will at least update the JavaDocs of the SynchronousRetrieval to mention the main thread as not being a good place to call it. Thanks for the contribution.
